[package]
name = "git-diary"
version = "0.1.0"
authors = ["joecargill <joe.cargill@slicelife.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
git2 = "0.13"
